### ISSUE TITLE
[BUG] Geckolib3 3.1.6 doesn't exist

### ISSUE THREAD

**Issue by jametaz** [Virus5600/Defensive-Measures-Mod#9]
Fabric loader 0.14.15 error: 
Mod 'Defensive Measures' (dm) 1.0.1-beta-1.19.2 requires version 3.1.6 or later of geckolib3, which is missing!

I've tried: 
geckolib-fabric-1.19.3-3.1.6
geckolib-fabric-1.19.3-3.1.7
geckolib-fabric-1.19.3-3.1.8
geckolib-fabric-1.19.3-3.1.9
geckolib-fabric-1.19.3-4.0.3
geckolib-fabric-1.19.3-4.0.4

None of them worked.
[Incompatible mod set.txt](https://github.com/Virus5600/Defensive-Measures-Mod/files/10830948/Incompatible.mod.set.txt)

**Comment by Virus5600** [comment]
May I know what mod loader you're using. Along with your Minecraft version and if there are other mods installed?

**Comment by jametaz** [comment]
> May I know what mod loader you're using. Along with your Minecraft version and if there are other mods installed?

No other mods except for Defensive Measures.

1.19.3 - Fabric Loader 0.14.17 + Fabric API 0.75.1

--Without adding Geckolib:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, version 3.1.6 or later.
Unmet dependency listing:
	 - Mod 'Defensive Measures' (dm) 1.0.1-beta-1.19.2 requires version 3.1.6 or later of geckolib3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

--After adding Geckolib  4.0.4:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, version 3.1.6 or later.
Unmet dependency listing:
	 - Mod 'Defensive Measures' (dm) 1.0.1-beta-1.19.2 requires version 3.1.6 or later of geckolib3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

On 1.19.2, Fabric 0.14.17, with API 0.75.1, no other mods, it just spits the attached crash.
[crash-2023-02-27_21.50.26-client.txt](https://github.com/Virus5600/Defensive-Measures-Mod/files/10846140/crash-2023-02-27_21.50.26-client.txt)

**Comment by Virus5600** [comment]
> --After adding Geckolib 4.0.4:
> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> - Install geckolib3, version 3.1.6 or later.

Geckolib 4 was just recently released and the mod isn't compatible with that version as of now. The change between Geckolib 3 and 4 is immense as it was a major update and that results to this crash. You'll have to do a downgrade from version 4 to version 3 to have the mod working. Let me know if that works out.

**Comment by jametaz** [comment]
Fabric 0.14.10 - DM 1.0.1 F/API 0.68.1
[crash-2023-02-27_22.32.24-client.txt](https://github.com/Virus5600/Defensive-Measures-Mod/files/10846307/crash-2023-02-27_22.32.24-client.txt)

**Comment by Virus5600** [comment]
I'll take a deeper look into it this coming weekend once school works have gone free a bit. Thank you.

**Comment by Virus5600** [comment]
Pardon me for the late reply. I've managed to track down the main problem. It seems like the current mod's version isn't compatible yet with 1.19.3 release of Minecraft. Various stuff was changed, which then requires an update to the mod.

As of the current, I'm working on it but it may take time as college stuff is upon me since it's our finals. You can play the mod with 1.19.2 fabric. I've also updated both the Modrinth and CurseForge information for the mod to prevent same issues from arising.

Thank you!

**Comment by Virus5600** [comment]
I forgot to mention this, but an update was released just recently. Version [Beta v1.0.2](https://modrinth.com/mod/defensive-measures/version/1.0.2-beta-1.19.2) might just help. Dependencies are also listed there as well.
